set pagesize 999
drop table if exists address
/
drop table if exists customer
/
create table customer (
    id      number generated by default on null as identity
            constraint customer_id_pk primary key,
    name    varchar2(255),
    active  varchar2(1 char) default on null 'Y' constraint active_check 
                   check (active in ('Y','N')) 
)
/
create table address (
    id             number generated by default on null as identity
                   constraint address_id_pk primary key,
    customer_id    number
                   constraint address_customer_id_fk
                   references customer on delete cascade,
    street         varchar2(80),
    city           varchar2(80),
    zip            varchar2(10),
    primary        varchar2(1 char) default on null 'N' constraint address_primary 
                   check (primary in ('Y','N')) 
)
/
-- table index
create index address_i1 on address (customer_id)
/
create or replace json relational duality view customers_dv as
customer @delete @insert @update @where(sql:"active='Y'")
  { _id            : id
    name           : name
    primaryAddress : address @where(sql:"primary='Y'")
                     {
                        id     : id
                        street : street
                        city   : city
                        zip    : zip
                      }

  }
/
create or replace json relational duality view customers2_dv as
customer @delete @insert @update @where(sql:"active='Y'")
  { _id            : id
    name           : name
    address @unnest @where(sql:"primary='Y'")
                     {
                        id     : id
                        street : street
                        city   : city
                        zip    : zip
                      }

  }
/
declare
    l_newcust_id number;
begin
    insert into customer(name)
    values ('Tesla')
    returning id into l_newcust_id;
    insert into address(customer_id,street,city,zip)
    values (l_newcust_id,'123 Nicola Drive','Fremont','91244');
    insert into address(customer_id,street,city,zip,primary)
    values (l_newcust_id,'1 Tesla Circle','Fremont','91244','Y');
    commit;
end;
/
select json_serialize(data pretty)
from customers_dv
where json_value(data,'$.name') = 'Tesla'
/
select json_serialize(data pretty)
from customers2_dv
where json_value(data,'$.name') = 'Tesla'
/